services:
  piper-tts:
    build: .
    image: local/piper-tts:latest
    volumes:
      - ./output:/app/output
    environment:
      PIPER_VOICE_DIR: /voices
    command: []
  piper-tts-ui:
    image: local/piper-tts:latest
    depends_on:
      - piper-tts
    environment:
      PIPER_VOICE_DIR: /voices
      PIPER_OUTPUT_DIR: /app/output
    volumes:
      - ./output:/app/output
    ports:
      - "7860:7860"
    command: ["python", "-m", "app.interface"]
